# Generated by Django 4.1.1 on 2022-11-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('date_of_birth', models.DateField()),
                ('avg_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('user_type', models.TextField(choices=[('private', 'Private'), ('company', 'Company')], default='private', max_length=7)),
                ('facebook', models.URLField(blank=True, default='')),
                ('instagram', models.URLField(blank=True, default='')),
                ('avatar', models.URLField(blank=True, default='')),
            ],
        ),
    ]
