# Generated by Django 4.1.2 on 2022-11-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_avg_rate_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avg_rate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
