version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5435:5432"
  web:
    build: .
    command: bash -c "pip install -r requirements.txt && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8003"
    volumes:
      - .:/users
    ports:
      - "8003:8003"
    depends_on:
      - db
      - rabbitmq2

#  rabbitmq2:
#    container_name: rabbitmq2
#    domainname: rabbitmq.com
#    image: rabbitmq:3.8-management-alpine
#    environment:
#      - RABBITMQ_DEFAULT_USER=admin
#      - RABBITMQ_DEFAULT_PASS=admin
#      - RABBITMQ_USERNAME=admin
#      - RABBITMQ_PASSWORD=admin
#      - RABBITMQ_DEFAULT_VHOST=/
##      - AMQP_SERVER_URL=amqp://guest:guest@rabbitmq:5672
#    ports:
#      # AMQP protocol port
#      - '5672:5672'
#      # HTTP management UI
#      - '15672:15672'
#    volumes:
#      - ./rabbitmq/log/:/var/log/rabbitmq/
#      - ./rabbitmq/data/:/var/lib/rabbitmq/
#    networks:
#      - rabbitmq_network

volumes:
  postgres_data:

