version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: bash -c "python users2Delete/manage.py makemigrations && python users2Delete/manage.py migrate && python users2Delete/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/users2Delete
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
